create extension if not exists pgcrypto;
create table if not exists properties(id uuid primary key default gen_random_uuid(),name text not null,address text,phone text,created_at timestamptz default now());
create table if not exists rooms(id uuid primary key default gen_random_uuid(),property_id uuid references properties(id) on delete cascade,room_code text not null,rent numeric(14,2) not null default 0,status text not null default 'available' check(status in ('available','occupied','maintenance')),created_at timestamptz default now(),unique(property_id,room_code));
create table if not exists tenants(id uuid primary key default gen_random_uuid(),property_id uuid references properties(id) on delete cascade,room_id uuid references rooms(id) on delete set null,name text not null,phone text,email text,start_date date,monthly_rent numeric(14,2) not null default 0,status text default 'active',created_at timestamptz default now());
create table if not exists invoices(id uuid primary key default gen_random_uuid(),property_id uuid references properties(id) on delete cascade,tenant_id uuid references tenants(id) on delete cascade,period date not null,amount numeric(14,2) not null,status text not null default 'unpaid' check(status in ('unpaid','paid','partial','cancelled')),due_date date,created_at timestamptz default now());
create table if not exists payments(id uuid primary key default gen_random_uuid(),invoice_id uuid references invoices(id) on delete cascade,amount numeric(14,2) not null,paid_at timestamptz default now(),method text default 'cash',note text);
create table if not exists expenses(id uuid primary key default gen_random_uuid(),property_id uuid references properties(id) on delete cascade,category text not null,description text,amount numeric(14,2) not null,spent_at date default current_date,created_at timestamptz default now());
create index if not exists rooms_property_idx on rooms(property_id); create index if not exists tenants_property_idx on tenants(property_id); create index if not exists invoices_property_idx on invoices(property_id);


-- Live booking tables used by the web booking flow
create table if not exists public.kost_rooms (
  id text primary key,
  tenant text not null default '-',
  price numeric not null default 0,
  status text not null check (status in ('available','occupied','maintenance')),
  updated_at timestamptz not null default now()
);

create table if not exists public.kost_bookings (
  id bigint generated by default as identity primary key,
  room_id text not null references public.kost_rooms(id),
  name text not null,
  phone text not null,
  start_date date not null,
  duration text not null default '1 bulan',
  status text not null default 'pending' check (status in ('pending','confirmed','cancelled')),
  created_at timestamptz not null default now()
);

create index if not exists kost_bookings_room_idx on public.kost_bookings(room_id);
create index if not exists kost_bookings_created_idx on public.kost_bookings(created_at desc);

alter table public.kost_rooms enable row level security;
alter table public.kost_bookings enable row level security;

drop policy if exists "public read available rooms" on public.kost_rooms;
create policy "public read available rooms" on public.kost_rooms
  for select using (status = 'available');

drop policy if exists "public create booking" on public.kost_bookings;
create policy "public create booking" on public.kost_bookings
  for insert with check (true);


-- Authentication mapping for property accounts
create table if not exists public.property_users (
  user_id uuid primary key references auth.users(id) on delete cascade,
  username text not null unique,
  property_id uuid references public.properties(id) on delete set null,
  created_at timestamptz not null default now()
);

alter table public.property_users enable row level security;
drop policy if exists "users read own property account" on public.property_users;
create policy "users read own property account" on public.property_users
  for select using (auth.uid() = user_id);


-- KMS MULTI-USER FOUNDATION — STAGE 1
-- Tenant isolation primitives for the authenticated application.

alter table public.properties
  add column if not exists owner_name text,
  add column if not exists manager text,
  add column if not exists currency text not null default 'IDR',
  add column if not exists logo text;

create or replace function public.current_property_id()
returns uuid
language sql
stable
security definer
set search_path = public
as $$
  select property_id
  from public.property_users
  where user_id = auth.uid()
  limit 1;
$$;

grant execute on function public.current_property_id() to authenticated;

alter table public.properties enable row level security;

drop policy if exists "property users read own property" on public.properties;
create policy "property users read own property"
  on public.properties for select
  using (id = public.current_property_id());

drop policy if exists "property users update own property" on public.properties;
create policy "property users update own property"
  on public.properties for update
  using (id = public.current_property_id())
  with check (id = public.current_property_id());

alter table public.rooms enable row level security;
alter table public.tenants enable row level security;
alter table public.invoices enable row level security;
alter table public.expenses enable row level security;

drop policy if exists "property users read own rooms" on public.rooms;
create policy "property users read own rooms" on public.rooms for select
  using (property_id = public.current_property_id());
drop policy if exists "property users insert own rooms" on public.rooms;
create policy "property users insert own rooms" on public.rooms for insert
  with check (property_id = public.current_property_id());
drop policy if exists "property users update own rooms" on public.rooms;
create policy "property users update own rooms" on public.rooms for update
  using (property_id = public.current_property_id())
  with check (property_id = public.current_property_id());
drop policy if exists "property users delete own rooms" on public.rooms;
create policy "property users delete own rooms" on public.rooms for delete
  using (property_id = public.current_property_id());

drop policy if exists "property users read own tenants" on public.tenants;
create policy "property users read own tenants" on public.tenants for select
  using (property_id = public.current_property_id());
drop policy if exists "property users insert own tenants" on public.tenants;
create policy "property users insert own tenants" on public.tenants for insert
  with check (property_id = public.current_property_id());
drop policy if exists "property users update own tenants" on public.tenants;
create policy "property users update own tenants" on public.tenants for update
  using (property_id = public.current_property_id())
  with check (property_id = public.current_property_id());
drop policy if exists "property users delete own tenants" on public.tenants;
create policy "property users delete own tenants" on public.tenants for delete
  using (property_id = public.current_property_id());

drop policy if exists "property users read own invoices" on public.invoices;
create policy "property users read own invoices" on public.invoices for select
  using (property_id = public.current_property_id());
drop policy if exists "property users insert own invoices" on public.invoices;
create policy "property users insert own invoices" on public.invoices for insert
  with check (property_id = public.current_property_id());
drop policy if exists "property users update own invoices" on public.invoices;
create policy "property users update own invoices" on public.invoices for update
  using (property_id = public.current_property_id())
  with check (property_id = public.current_property_id());
drop policy if exists "property users delete own invoices" on public.invoices;
create policy "property users delete own invoices" on public.invoices for delete
  using (property_id = public.current_property_id());

drop policy if exists "property users read own expenses" on public.expenses;
create policy "property users read own expenses" on public.expenses for select
  using (property_id = public.current_property_id());
drop policy if exists "property users insert own expenses" on public.expenses;
create policy "property users insert own expenses" on public.expenses for insert
  with check (property_id = public.current_property_id());
drop policy if exists "property users update own expenses" on public.expenses;
create policy "property users update own expenses" on public.expenses for update
  using (property_id = public.current_property_id())
  with check (property_id = public.current_property_id());
drop policy if exists "property users delete own expenses" on public.expenses;
create policy "property users delete own expenses" on public.expenses for delete
  using (property_id = public.current_property_id());


-- KMS MULTI-USER — STAGES 3-6: payment isolation
alter table public.payments enable row level security;

drop policy if exists "property users read own payments" on public.payments;
create policy "property users read own payments" on public.payments for select
  using (exists (
    select 1 from public.invoices i
    where i.id = payments.invoice_id
      and i.property_id = public.current_property_id()
  ));

drop policy if exists "property users insert own payments" on public.payments;
create policy "property users insert own payments" on public.payments for insert
  with check (exists (
    select 1 from public.invoices i
    where i.id = payments.invoice_id
      and i.property_id = public.current_property_id()
  ));

drop policy if exists "property users update own payments" on public.payments;
create policy "property users update own payments" on public.payments for update
  using (exists (
    select 1 from public.invoices i
    where i.id = payments.invoice_id
      and i.property_id = public.current_property_id()
  ))
  with check (exists (
    select 1 from public.invoices i
    where i.id = payments.invoice_id
      and i.property_id = public.current_property_id()
  ));

drop policy if exists "property users delete own payments" on public.payments;
create policy "property users delete own payments" on public.payments for delete
  using (exists (
    select 1 from public.invoices i
    where i.id = payments.invoice_id
      and i.property_id = public.current_property_id()
  ));

create index if not exists payments_invoice_idx on public.payments(invoice_id);
