'use client';
import{useEffect,useState}from'react';
type S={name:string;phone:string;address:string;currency:string;manager:string;logo:string;signature:string;receiptPrefix:string;receiptNext:number};
const d:S={name:'Kost Harmoni',phone:'0812-0000-0000',address:'Alamat properti',currency:'IDR',manager:'Pengelola Kost',logo:'',signature:'',receiptPrefix:'KW',receiptNext:1};
export default function Pengaturan(){const[f,setF]=useState<S>(d),[saved,setSaved]=useState(false);
useEffect(()=>{try{const x=localStorage.getItem('kostpro_settings');if(x)setF({...d,...JSON.parse(x)})}catch{}},[]);
const set=(k:keyof S,v:string|number)=>setF(x=>({...x,[k]:v}));
const image=(k:'logo'|'signature')=>(e:React.ChangeEvent<HTMLInputElement>)=>{const file=e.target.files?.[0];if(!file)return;if(file.size>1024*1024)return alert('File maksimal 1 MB.');const r=new FileReader();r.onload=()=>set(k,String(r.result));r.readAsDataURL(file)};
const save=()=>{localStorage.setItem('kostpro_settings',JSON.stringify(f));setSaved(true);setTimeout(()=>setSaved(false),2500)};
return <><div className="top"><div><div className="title">Pengaturan</div><div className="sub">Profil kost, identitas kwitansi dan penomoran</div></div></div><div className="card"><div className="section-title">Profil Kost</div><div className="form"><div className="field"><label>Nama Kost</label><input value={f.name} onChange={e=>set('name',e.target.value)}/></div><div className="field"><label>Nomor Telepon</label><input value={f.phone} onChange={e=>set('phone',e.target.value)}/></div><div className="field full"><label>Alamat Lengkap</label><textarea value={f.address} onChange={e=>set('address',e.target.value)} rows={3}/></div><div className="field"><label>Nama Pengelola</label><input value={f.manager} onChange={e=>set('manager',e.target.value)}/></div><div className="field"><label>Mata Uang</label><select value={f.currency} onChange={e=>set('currency',e.target.value)}><option>IDR — Rupiah Indonesia</option></select></div><div className="field"><label>Logo Kost</label><input type="file" accept="image/png,image/jpeg,image/webp" onChange={image('logo')}/>{f.logo&&<img src={f.logo} alt="Logo" style={{maxWidth:140,maxHeight:70,marginTop:8,objectFit:'contain'}}/>}</div><div className="field"><label>Tanda Tangan Digital</label><input type="file" accept="image/png,image/jpeg,image/webp" onChange={image('signature')}/>{f.signature&&<img src={f.signature} alt="Tanda tangan" style={{maxWidth:180,maxHeight:70,marginTop:8,objectFit:'contain'}}/>}</div></div></div><div className="card" style={{marginTop:18}}><div className="section-title">Penomoran Kwitansi</div><div className="form"><div className="field"><label>Prefix</label><input value={f.receiptPrefix} onChange={e=>set('receiptPrefix',e.target.value.toUpperCase())}/></div><div className="field"><label>Nomor Berikutnya</label><input type="number" min={1} value={f.receiptNext} onChange={e=>set('receiptNext',Math.max(1,Number(e.target.value)||1))}/></div></div><div className="sub" style={{marginTop:10}}>Format otomatis: {f.receiptPrefix}-{new Date().getFullYear()}-{String(f.receiptNext).padStart(5,'0')}</div><div className="actions"><button className="btn" onClick={save}>Simpan Pengaturan</button></div>{saved&&<div className="sub" style={{marginTop:12,color:'#047857',fontWeight:700}}>✓ Pengaturan berhasil disimpan.</div>}</div></>}
