'use client';
import{useState}from'react';
import{useRouter}from'next/navigation';
export default function Daftar(){
 const router=useRouter();const[f,setF]=useState({name:'',ownerName:'',username:'',password:'',phone:'',address:''});const[msg,setMsg]=useState('');
 const set=(k:string,v:string)=>setF(x=>({...x,[k]:v}));
 const submit=async()=>{setMsg('');if(!f.name||!f.username||f.password.length<6)return setMsg('Nama kost, username, dan password minimal 6 karakter wajib diisi.');const r=await fetch('/api/auth/register',{method:'POST',headers:{'Content-Type':'application/json'},body:JSON.stringify(f)});const d=await r.json();if(!r.ok)return setMsg(d.error||'Gagal mendaftarkan properti.');setMsg('Properti berhasil didaftarkan. Silakan login.');setTimeout(()=>router.replace('/login'),700)};
 return <div style={{maxWidth:620,margin:'5vh auto'}}><div className="card"><div className="title">Daftar Properti</div><div className="sub" style={{marginBottom:20}}>Setiap pendaftaran membuat tenant/property sendiri. Data antar properti tidak digabung.</div><div className="form"><div className="field"><label>Nama Kost</label><input value={f.name} onChange={e=>set('name',e.target.value)}/></div><div className="field"><label>Nama Pemilik</label><input value={f.ownerName} onChange={e=>set('ownerName',e.target.value)}/></div><div className="field"><label>Username Login</label><input value={f.username} onChange={e=>set('username',e.target.value)}/></div><div className="field"><label>Password</label><input type="password" value={f.password} onChange={e=>set('password',e.target.value)}/></div><div className="field"><label>Telepon</label><input value={f.phone} onChange={e=>set('phone',e.target.value)}/></div><div className="field full"><label>Alamat</label><textarea rows={3} value={f.address} onChange={e=>set('address',e.target.value)}/></div></div>{msg&&<div className="sub" style={{marginTop:14,fontWeight:700}}>{msg}</div>}<div className="actions" style={{marginTop:18}}><button className="btn" onClick={submit}>Daftarkan Properti</button><button className="btn secondary" onClick={()=>router.push('/login')}>Sudah punya akun</button></div></div></div>
}
