'use client';

import { useEffect, useState } from 'react';
import { supabase } from '@/lib/supabase-browser';
import { currentPropertyId } from '@/lib/property';
import { money } from '@/lib/store';

type Invoice={id:string;tenant_id:string;period:string;amount:number;status:string;due_date:string|null};
type Tenant={id:string;name:string};
export default function Tagihan(){
 const[i,setI]=useState<Invoice[]>([]),[t,setT]=useState<Tenant[]>([]),[show,setShow]=useState(false),[tenant,setTenant]=useState(''),[amount,setAmount]=useState(''),[period,setPeriod]=useState(new Date().toISOString().slice(0,7)+'-01'),[due,setDue]=useState(''),[selected,setSelected]=useState(''),[method,setMethod]=useState('transfer'),[msg,setMsg]=useState('');
 const load=async()=>{try{const pid=await currentPropertyId();const[a,b]=await Promise.all([supabase.from('invoices').select('id,tenant_id,period,amount,status,due_date').eq('property_id',pid).order('period',{ascending:false}),supabase.from('tenants').select('id,name').eq('property_id',pid).eq('status','active').order('name')]);if(a.error)throw a.error;if(b.error)throw b.error;setI((a.data||[]) as Invoice[]);setT((b.data||[]) as Tenant[])}catch{setMsg('Gagal memuat tagihan.')}};
 useEffect(()=>{load()},[]);
 const create=async()=>{if(!tenant||!amount||!period)return setMsg('Penghuni, periode, dan nominal wajib diisi.');try{const pid=await currentPropertyId();const{error}=await supabase.from('invoices').insert({property_id:pid,tenant_id:tenant,period,amount:Number(amount),status:'unpaid',due_date:due||null});if(error)throw error;setShow(false);setAmount('');setTenant('');setMsg('Tagihan berhasil dibuat.');await load()}catch{setMsg('Gagal membuat tagihan.')}};
 const pay=async()=>{const x=i.find(v=>v.id===selected);if(!x)return setMsg('Pilih tagihan.');if(x.status==='paid')return setMsg('Tagihan sudah lunas.');try{const{error}=await supabase.from('payments').insert({invoice_id:x.id,amount:x.amount,method,paid_at:new Date().toISOString()});if(error)throw error;const{error:updateError}=await supabase.from('invoices').update({status:'paid'}).eq('id',x.id);if(updateError)throw updateError;setSelected('');setMsg('Pembayaran berhasil dicatat.');await load()}catch{setMsg('Gagal mencatat pembayaran.')}};
 return <><div className="top"><div><div className="title">Tagihan & Pembayaran</div><div className="sub">Invoice dan pembayaran sekarang tersimpan terpisah per properti.</div></div><button className="btn" onClick={()=>setShow(!show)}>+ Buat Tagihan</button></div>{msg&&<div className="card" style={{marginBottom:18}}>{msg}</div>}{show&&<div className="card" style={{marginBottom:18}}><div className="section-title">Buat Tagihan</div><div className="form"><div className="field"><label>Penghuni</label><select value={tenant} onChange={e=>{setTenant(e.target.value);const x=t.find(v=>v.id===e.target.value);}}><option value="">Pilih penghuni</option>{t.map(x=><option key={x.id} value={x.id}>{x.name}</option>)}</select></div><div className="field"><label>Periode</label><input type="date" value={period} onChange={e=>setPeriod(e.target.value)}/></div><div className="field"><label>Nominal</label><input type="number" value={amount} onChange={e=>setAmount(e.target.value)}/></div><div className="field"><label>Jatuh Tempo</label><input type="date" value={due} onChange={e=>setDue(e.target.value)}/></div></div><div className="actions"><button className="btn" onClick={create}>Simpan Tagihan</button><button className="btn secondary" onClick={()=>setShow(false)}>Batal</button></div></div>}<div className="card"><table className="table"><thead><tr><th>Penghuni</th><th>Periode</th><th>Nominal</th><th>Jatuh Tempo</th><th>Status</th><th>Aksi</th></tr></thead><tbody>{i.map(x=><tr key={x.id}><td><b>{t.find(v=>v.id===x.tenant_id)?.name||x.tenant_id}</b></td><td>{x.period}</td><td>{money(Number(x.amount))}</td><td>{x.due_date||'-'}</td><td><span className={'badge '+(x.status==='paid'?'green':x.status==='partial'?'amber':'red')}>{x.status==='paid'?'Lunas':x.status==='partial'?'Sebagian':'Belum Bayar'}</span></td><td>{x.status!=='paid'&&<button className="btn secondary" onClick={()=>setSelected(x.id)}>Bayar</button>}</td></tr>)}</tbody></table></div>{selected&&<div className="card" style={{marginTop:18}}><div className="section-title">Catat Pembayaran</div><div className="form"><div className="field"><label>Metode</label><select value={method} onChange={e=>setMethod(e.target.value)}><option value="transfer">Transfer</option><option value="cash">Cash</option><option value="qris">QRIS</option></select></div></div><div className="actions"><button className="btn" onClick={pay}>Simpan Pembayaran</button><button className="btn secondary" onClick={()=>setSelected('')}>Batal</button></div></div>}</>;
}