'use client';

import { useEffect, useState } from 'react';
import { supabase } from '@/lib/supabase-browser';
import { currentPropertyId } from '@/lib/property';
import { money } from '@/lib/store';

type Room={id:string;room_code:string;rent:number;status:string};
type Tenant={id:string;name:string;room_id:string|null;phone:string;start_date:string|null;monthly_rent:number;status:string};
export default function Penghuni(){
 const[t,setT]=useState<Tenant[]>([]),[r,setR]=useState<Room[]>([]),[show,setShow]=useState(false),[name,setName]=useState(''),[room,setRoom]=useState(''),[phone,setPhone]=useState(''),[date,setDate]=useState(new Date().toISOString().slice(0,10)),[rent,setRent]=useState(''),[msg,setMsg]=useState('');
 const load=async()=>{try{const pid=await currentPropertyId();const[tr,rr]=await Promise.all([supabase.from('tenants').select('id,name,room_id,phone,start_date,monthly_rent,status').eq('property_id',pid).eq('status','active').order('name'),supabase.from('rooms').select('id,room_code,rent,status').eq('property_id',pid).order('room_code')]);if(tr.error)throw tr.error;if(rr.error)throw rr.error;setT((tr.data||[]) as Tenant[]);setR((rr.data||[]) as Room[]);}catch{setMsg('Gagal memuat penghuni.')}};
 useEffect(()=>{load()},[]);
 const add=async()=>{const rm=r.find(x=>x.id===room);if(!name.trim()||!rm)return setMsg('Nama dan kamar wajib diisi.');if(rm.status!=='available')return setMsg('Kamar tidak tersedia.');const monthlyRent=Number(rent)||Number(rm.rent);try{const pid=await currentPropertyId();const{data:newTenant,error}=await supabase.from('tenants').insert({property_id:pid,room_id:rm.id,name:name.trim(),phone:phone.trim(),start_date:date,monthly_rent:monthlyRent,status:'active'}).select('id').single();if(error||!newTenant)throw error||new Error('tenant');const{error:invoiceError}=await supabase.from('invoices').insert({property_id:pid,tenant_id:newTenant.id,period:date.slice(0,7)+'-01',amount:monthlyRent,status:'unpaid'});if(invoiceError)throw invoiceError;await supabase.from('rooms').update({status:'occupied'}).eq('id',rm.id);setName('');setRoom('');setPhone('');setRent('');setShow(false);setMsg('Penghuni berhasil ditambahkan.');await load()}catch{setMsg('Gagal menyimpan penghuni.')}};
 const checkout=async(x:Tenant)=>{if(!confirm('Check out penghuni ini?'))return;try{await supabase.from('tenants').update({status:'history'}).eq('id',x.id);if(x.room_id)await supabase.from('rooms').update({status:'available'}).eq('id',x.room_id);setMsg('Penghuni dipindahkan ke status history dan kamar dikosongkan.');await load()}catch{setMsg('Gagal checkout.')}};
 return <><div className="top"><div><div className="title">Penghuni Aktif</div><div className="sub">Data penghuni tersimpan per properti dan dilindungi RLS.</div></div><button className="btn" onClick={()=>setShow(!show)}>+ Tambah Penghuni</button></div>{msg&&<div className="card" style={{marginBottom:18}}>{msg}</div>}{show&&<div className="card" style={{marginBottom:18}}><div className="section-title">Tambah Penghuni</div><div className="form"><div className="field"><label>Nama</label><input value={name} onChange={e=>setName(e.target.value)}/></div><div className="field"><label>Kamar</label><select value={room} onChange={e=>{setRoom(e.target.value);const x=r.find(y=>y.id===e.target.value);if(x)setRent(String(x.rent))}}><option value="">Pilih kamar</option>{r.filter(x=>x.status==='available').map(x=><option key={x.id} value={x.id}>{x.room_code} — {money(Number(x.rent))}</option>)}</select></div><div className="field"><label>Telepon</label><input value={phone} onChange={e=>setPhone(e.target.value)}/></div><div className="field"><label>Mulai Sewa</label><input type="date" value={date} onChange={e=>setDate(e.target.value)}/></div><div className="field"><label>Sewa / bulan</label><input type="number" value={rent} onChange={e=>setRent(e.target.value)}/></div></div><div className="actions"><button className="btn" onClick={add}>Simpan Penghuni</button><button className="btn secondary" onClick={()=>setShow(false)}>Batal</button></div></div>}<div className="card"><table className="table"><thead><tr><th>Nama</th><th>Kamar</th><th>Telepon</th><th>Mulai</th><th>Sewa</th><th>Aksi</th></tr></thead><tbody>{t.map(x=><tr key={x.id}><td><b>{x.name}</b></td><td>{r.find(y=>y.id===x.room_id)?.room_code||'-'}</td><td>{x.phone||'-'}</td><td>{x.start_date||'-'}</td><td>{money(Number(x.monthly_rent))}</td><td><button className="btn" onClick={()=>checkout(x)}>C.O</button></td></tr>)}</tbody></table>{!t.length&&<div className="sub" style={{padding:20}}>Belum ada penghuni aktif.</div>}</div></>;
}