export type RoomStatus='occupied'|'available'|'maintenance';export type Room={id:string;tenant:string;price:number;status:RoomStatus};export type Payment={receiptNo?:string;id:string;tenant:string;room:string;month:string;amount:number;status:'paid'|'unpaid';paidAt?:string;method?:string};export type Tenant={id:string;name:string;room:string;phone:string;startDate:string;rent:number;endDate?:string;status?:'active'|'history';checkoutReason?:'checkout'|'expired'|'transferred'};export type Transaction={id:string;date:string;description:string;category:string;amount:number;type:'income'|'expense';referenceId?:string};
export const defaultRooms:Room[]=[{id:'K-01',tenant:'Andi Pratama',price:1200000,status:'occupied'},{id:'K-02',tenant:'Siti Rahma',price:1200000,status:'occupied'},{id:'K-03',tenant:'-',price:1200000,status:'available'},{id:'K-04',tenant:'Budi Santoso',price:1300000,status:'occupied'},{id:'K-05',tenant:'-',price:1300000,status:'maintenance'},{id:'K-06',tenant:'-',price:1400000,status:'available'}];
export const defaultTenants:Tenant[]=[{id:'T-01',name:'Andi Pratama',room:'K-01',phone:'0812-xxxx-1122',startDate:'2026-09-01',rent:1200000,status:'active'},{id:'T-02',name:'Siti Rahma',room:'K-02',phone:'0813-xxxx-2233',startDate:'2026-09-01',rent:1200000,status:'active'},{id:'T-03',name:'Budi Santoso',room:'K-04',phone:'0814-xxxx-3344',startDate:'2026-08-15',rent:1300000,status:'active'}];
export const defaultPayments:Payment[]=[{id:'P-01',tenant:'Andi Pratama',room:'K-01',month:'September 2026',amount:1200000,status:'paid',paidAt:'2026-09-05',method:'transfer'},{id:'P-02',tenant:'Siti Rahma',room:'K-02',month:'September 2026',amount:1200000,status:'paid',paidAt:'2026-09-05',method:'cash'},{id:'P-03',tenant:'Budi Santoso',room:'K-04',month:'September 2026',amount:1300000,status:'unpaid'}];
export const defaultTransactions:Transaction[]=[{id:'TR-01',date:'2026-09-05',description:'Pelunasan sewa Andi Pratama — K-01 — September 2026',category:'Pendapatan sewa',amount:1200000,type:'income',referenceId:'P-01'},{id:'TR-02',date:'2026-09-05',description:'Pelunasan sewa Siti Rahma — K-02 — September 2026',category:'Pendapatan sewa',amount:1200000,type:'income',referenceId:'P-02'},{id:'TR-03',date:'2026-09-18',description:'Listrik',category:'Utilitas',amount:450000,type:'expense'},{id:'TR-04',date:'2026-09-15',description:'Internet',category:'Utilitas',amount:400000,type:'expense'}];

const SCOPE_KEY='kostpro_active_scope';
type Scope={userId:string;propertyId:string};
function readScope():Scope|null{if(typeof window==='undefined')return null;try{const raw=localStorage.getItem(SCOPE_KEY);if(!raw)return null;const value=JSON.parse(raw);if(typeof value?.userId==='string'&&typeof value?.propertyId==='string'&&value.userId&&value.propertyId)return value;return null}catch{return null}}
export function setActivePropertyScope(userId:string,propertyId:string){if(typeof window==='undefined')return;localStorage.setItem(SCOPE_KEY,JSON.stringify({userId,propertyId}))}
export function clearActivePropertyScope(){if(typeof window==='undefined')return;localStorage.removeItem(SCOPE_KEY)}
export function getActivePropertyScope(){return readScope()}
function scopedKey(name:string){const scope=readScope();return scope?'kostpro_'+scope.userId+'_'+scope.propertyId+'_'+name:null}
export function loadData<T>(name:string,fallback:T):T{if(typeof window==='undefined')return fallback;try{const key=scopedKey(name);if(!key)return fallback;const v=localStorage.getItem(key);return v?JSON.parse(v):fallback}catch{return fallback}}
export function saveData<T>(name:string,v:T){if(typeof window==='undefined')return;const key=scopedKey(name);if(key)localStorage.setItem(key,JSON.stringify(v))}
export function syncPaymentTransactions():Transaction[]{if(typeof window==='undefined')return defaultTransactions;const active=loadData<Payment[]>('payments',defaultPayments);const history=loadData<Payment[]>('paymentHistory',[]);const paid=[...history,...active.filter(p=>p.status==='paid'&&!history.some(h=>h.id===p.id))];let tx=loadData<Transaction[]>('transactions',defaultTransactions);let changed=false;for(const p of paid){if(!tx.some(x=>x.referenceId===p.id)){tx=[...tx,{id:'TR-'+Date.now()+'-'+Math.random().toString(36).slice(2,7),date:p.paidAt||new Date().toISOString().slice(0,10),description:'Pelunasan sewa '+p.tenant+' — '+p.room+' — '+p.month,category:'Pendapatan sewa',amount:Number(p.amount)||0,type:'income',referenceId:p.id}];changed=true}}if(changed)saveData('transactions',tx);return tx}
export const money=(n:number)=>new Intl.NumberFormat('id-ID',{style:'currency',currency:'IDR',maximumFractionDigits:0}).format(Number(n)||0);
